name: 🐛 Bug Report
description: Something's glitching or broken? Let's squash it!
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### 💻 What's broken?

        Thanks for helping us keep bloom cozy and functional 🌸
  - type: input
    id: title
    attributes:
      label: Bug title
      description: Short & clear summary of the issue
      placeholder: e.g. "XP bar does not update after ritual"
      validations:
        required: true
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: What steps caused the bug?
      placeholder: Clicked this, opened that, boom, bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: “I expected the XP to go up, and for my avatar to sparkle ✨”
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, version, anything else helpful
